global:
  scrape_interval:     15s

scrape_configs:
- job_name: 'prometheus'
  static_configs:
  - targets: ['localhost:9090']

- job_name: 'petbook-dynamodb-java'
  metrics_path: '/petbook/actuator/prometheus'
  scrape_interval: 5s
  static_configs:
  - targets: ['host.docker.internal:8080']
